package AdvancedJavaa;
import javax.swing.*;
public class Swing{
    public static void main(String[] args){
        // Swing is a GUI widget toolkit for java. It is part of java foundation
        //  classes (JFC) and provides a set of GUI components for java programs. 
        // Swing is built on top of AWT (Abstract Window Toolkit) and provides a
        //  more sophisticated set of GUI components than AWT. Swing provides a 
        // pluggable look and feel, which allows the user to change the look and
        //  feel of the application at runtime. Swing also provides a set of layout 
        // managers, which allow the user to arrange the components in the container
        //  in a specific way. Swing also provides a set of event listeners, which
        //  allow the user to handle events generated by the components.
        JFrame frame=new JFrame("swing example");
        frame.setSize(400,400);
        frame.setLayout(null);
        frame.setVisible(true);
        JButton button=new JButton(new ImageIcon("Practice, Project/AdvancedJavaa/psitlogo.png"));
        button.setBounds(120,100,100,40);
        frame.add(button);
    }

}